<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_DDOS Attack Map_fullScreenThreatwayA_fe63ad</name>
   <tag></tag>
   <elementGuidId>59ca30ab-18ee-40b3-8841-ab38f21c549f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fullScreenThreatwayAttackMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullScreenThreatwayAttackMap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Threatway DDOS Attack Map&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>691c5f49-3a68-4cf0-97b1-0c418b02dab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullScreenThreatwayAttackMap</value>
      <webElementGuid>d77d4eb5-b318-4aea-b3cc-f70bb174c9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Threatway DDOS Attack Map</value>
      <webElementGuid>8c0dee20-e31c-45e6-a497-d4d353fc634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://threatway-map.catchprobe.org/static/en.html</value>
      <webElementGuid>9a74edc8-7f89-4e60-b345-def98ea09a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullScreenThreatwayAttackMap&quot;)</value>
      <webElementGuid>28a85bcd-49a4-43f1-94fe-80b2ccc574de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fullScreenThreatwayAttackMap']</value>
      <webElementGuid>00e43aee-609c-4044-8069-afc88262d0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/iframe</value>
      <webElementGuid>d1d0eac0-b828-46ba-894e-8f1749e220c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9f66beda-654a-423e-82cb-a4020fb7584c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fullScreenThreatwayAttackMap' and @title = 'Threatway DDOS Attack Map' and @src = 'https://threatway-map.catchprobe.org/static/en.html']</value>
      <webElementGuid>5b3a5c63-b257-4d11-952b-96321a849b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
