<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Saldr No_leaflet-zoom-animated</name>
   <tag></tag>
   <elementGuidId>72fed0e8-528a-408a-af99-3a0e9c14824e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.leaflet-zoom-animated</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>svg</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8ee38b99-c877-4103-9063-d6ec81843281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-zoom-animated</value>
      <webElementGuid>11287553-007d-4ab6-badb-74fe9e08ae3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>928</value>
      <webElementGuid>4b83833f-0a2c-4637-9cd2-9fbcc8e19d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>283</value>
      <webElementGuid>5397b13b-88f3-4163-8a81-fb43b5c878c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-overlay-pane&quot;]/svg[@class=&quot;leaflet-zoom-animated&quot;]</value>
      <webElementGuid>788f57df-519e-462c-b233-8cb612aa64c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/otp/Page_/Page_/iframe_DDOS Attack Map_fullScreenThreatwayA_fe63ad</value>
      <webElementGuid>cd72b6b6-bb60-4880-8b17-21560b68ec72</webElementGuid>
   </webElementProperties>
</WebElementEntity>
