<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DateCriticalityID</name>
   <tag></tag>
   <elementGuidId>a3b2c503-b9f5-4062-bce3-80e464321c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[3]/div/div/div/div/form/div[3]/div/div/div/div[10]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Sort Field : DateDateCriticalityID$/ >> select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>32995830-ce7b-4908-a6ba-3adc4f04694a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9745d1fa-7f48-4f44-9250-4b6cff5d17ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4261d8f6-981e-491d-8974-cb0a5eb05c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DateCriticalityID</value>
      <webElementGuid>dfe15d71-f5b1-4257-b468-c253e6c37f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[3]/div[@class=&quot;w-full lg:flex lg:justify-between&quot;]/div[@class=&quot;flex flex-1 flex-col gap-2 lg:flex-row&quot;]/div[1]/div[@class=&quot;fixed top-[89px] z-[9] flex h-[calc(100%-89px)] w-60 flex-col bg-background transition-all duration-300 lg:block 2xl:w-80 left-24&quot;]/form[@class=&quot;flex h-[calc(100%-68px)] w-full flex-col rounded-md bg-card shadow-md&quot;]/div[@class=&quot;flex-1 overflow-hidden&quot;]/div[@class=&quot;relative overflow-hidden h-full w-full&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;space-y-2 mx-4 mb-4&quot;]/select[1]</value>
      <webElementGuid>a2f42db0-4fce-4572-ade6-a50fb32aa40b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[3]/div/div/div/div/form/div[3]/div/div/div/div[10]/select</value>
      <webElementGuid>c2922e7e-a989-4631-8067-4cd7b0a0b287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::select[1]</value>
      <webElementGuid>dd2eb917-e852-4009-9589-dfe9e744d517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Field :'])[1]/following::select[1]</value>
      <webElementGuid>ded88185-7828-4aa2-82bd-0d89e4dfb54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLY AND SEARCH'])[1]/preceding::select[1]</value>
      <webElementGuid>f7de6137-b1ee-4d23-b3b7-99998fdabd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILTER OPTIONS'])[1]/preceding::select[1]</value>
      <webElementGuid>8147024a-14b1-464c-8417-3245a4263d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>69619832-0125-46a2-badf-8d2dcc6f0bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'DateCriticalityID' or . = 'DateCriticalityID')]</value>
      <webElementGuid>3ad8d648-20f9-4652-800c-e6a87ba62bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
