<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CloudflareDropdownSelect</name>
   <tag></tag>
   <elementGuidId>ff1f2e8a-a316-45c9-a3e9-c226c0490c7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
