<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cloudflareentegration</name>
   <tag></tag>
   <elementGuidId>cea15c04-e2ac-4706-af50-18c97408d39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[text()='cloudflareIntegration']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
