<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Attack Map_fullScreenAttackMap</name>
   <tag></tag>
   <elementGuidId>a5a827ba-ed42-485c-8541-b07546e2d0a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fullScreenAttackMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullScreenAttackMap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Smart Deceptive Attack Map&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f7a18412-c1e2-42ed-8f19-24d4a60374dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullScreenAttackMap</value>
      <webElementGuid>68551470-6e4f-468e-bc95-c4894ed0ff5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Smart Deceptive Attack Map</value>
      <webElementGuid>90569cd2-67e0-4a23-817f-689a458eb459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://smartdeceptive-attackmap.catchprobe.org/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NDcxNDc2NSwianRpIjoiMDdkZDFmY2YtMTg1Mi00NGYyLWI0OTEtYzNkMTliZWUxZDA2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJzdWJkb21haW4iOiJwbGF0Zm9ybSIsImlkIjoiNjRlNWI1MmU2NmRkZjJkMGUzMTkxNTc0IiwiZW1haWwiOiJmYXRpaC55dWtzZWxAY2F0Y2hwcm9iZS5jb20iLCJmdWxsbmFtZSI6IkZhdGloIFlcdTAwZmNrc2VsIiwiY29tcGFueSI6IjYwOTFiY2RjM2VkNjhjYmZhZDg3NWJkYiIsImNyZWF0ZWRfYXQiOjE3NDQ3MTQ3NjUuNzg2MjY3fSwibmJmIjoxNzQ0NzE0NzY1LCJleHAiOjE3NDczMDY3NjV9.qg23-tXaYJPneRolkS2cHc_075jmvhE__k2khiRgMrM&amp;organisation_id=65fa9be06663e40146ac88f9</value>
      <webElementGuid>dd871ebc-c24d-44fd-9d37-90cfe5301303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullScreenAttackMap&quot;)</value>
      <webElementGuid>2c151c35-0639-46fb-858d-8cbec6ff3aad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fullScreenAttackMap']</value>
      <webElementGuid>824f024b-5c0d-4dfe-be5b-8d7e15ace36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/iframe</value>
      <webElementGuid>c8c789a8-72c2-447f-9402-c88e0fc0d973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8f7d2fc0-6d25-4564-83a1-f7c26259ab49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fullScreenAttackMap' and @title = 'Smart Deceptive Attack Map' and @src = 'https://smartdeceptive-attackmap.catchprobe.org/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NDcxNDc2NSwianRpIjoiMDdkZDFmY2YtMTg1Mi00NGYyLWI0OTEtYzNkMTliZWUxZDA2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJzdWJkb21haW4iOiJwbGF0Zm9ybSIsImlkIjoiNjRlNWI1MmU2NmRkZjJkMGUzMTkxNTc0IiwiZW1haWwiOiJmYXRpaC55dWtzZWxAY2F0Y2hwcm9iZS5jb20iLCJmdWxsbmFtZSI6IkZhdGloIFlcdTAwZmNrc2VsIiwiY29tcGFueSI6IjYwOTFiY2RjM2VkNjhjYmZhZDg3NWJkYiIsImNyZWF0ZWRfYXQiOjE3NDQ3MTQ3NjUuNzg2MjY3fSwibmJmIjoxNzQ0NzE0NzY1LCJleHAiOjE3NDczMDY3NjV9.qg23-tXaYJPneRolkS2cHc_075jmvhE__k2khiRgMrM&amp;organisation_id=65fa9be06663e40146ac88f9']</value>
      <webElementGuid>ff2e26bf-ede2-4a36-8a41-f432fb8ebb88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
