<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Attack Map_fullScreenAttackMap</name>
   <tag></tag>
   <elementGuidId>73f57234-9ed0-4db6-85c9-3bf5644e21c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fullScreenAttackMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullScreenAttackMap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Smart Deceptive Attack Map&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>efc0bdc0-8a58-4ae2-9aa6-7eba7939ab88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullScreenAttackMap</value>
      <webElementGuid>9bbdee08-678c-415d-b9ee-3fc0edf10445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Smart Deceptive Attack Map</value>
      <webElementGuid>c707a559-a109-446e-9746-1a3816baf9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://smartdeceptive-attackmap.catchprobe.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NDcxODQ4OSwianRpIjoiODVkYzAyMjItNzY4Zi00MGRlLWI3NGUtZGYyZjAzMWNhM2M2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJzdWJkb21haW4iOiJwbGF0Zm9ybSIsImlkIjoiNjRmMDdkMjdhY2M1NWNkMmQ3NmNlZGMyIiwiZW1haWwiOiJmYXRpaC55dWtzZWxAY2F0Y2hwcm9iZS5jb20iLCJmdWxsbmFtZSI6ImZhdGloIHl1a3NlbCIsImNvbXBhbnkiOiI2MDkxYmNkYzNlZDY4Y2JmYWQ4NzViZGIiLCJjcmVhdGVkX2F0IjoxNzQ0NzE4NDg5Ljg1NjIyNH0sIm5iZiI6MTc0NDcxODQ4OSwiZXhwIjoxNzQ3MzEwNDg5fQ.9F2guuzzYhdEpqtfYOla2UfPmQyR81UGT0G5nEwaPBE&amp;organisation_id=662bc6d80dd10297670de9f4</value>
      <webElementGuid>1d16f913-3bdc-4e6b-a006-28ec2b464fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullScreenAttackMap&quot;)</value>
      <webElementGuid>c8bb91cb-797a-441f-aab1-69d896fe3614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fullScreenAttackMap']</value>
      <webElementGuid>628ce4d6-8906-4bca-b07d-7b854f313ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/iframe</value>
      <webElementGuid>9bd8f1a7-926a-4172-ab67-b2e71a864fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cdb2dae1-c155-41f9-88f0-5919176188f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fullScreenAttackMap' and @title = 'Smart Deceptive Attack Map' and @src = 'https://smartdeceptive-attackmap.catchprobe.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NDcxODQ4OSwianRpIjoiODVkYzAyMjItNzY4Zi00MGRlLWI3NGUtZGYyZjAzMWNhM2M2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJzdWJkb21haW4iOiJwbGF0Zm9ybSIsImlkIjoiNjRmMDdkMjdhY2M1NWNkMmQ3NmNlZGMyIiwiZW1haWwiOiJmYXRpaC55dWtzZWxAY2F0Y2hwcm9iZS5jb20iLCJmdWxsbmFtZSI6ImZhdGloIHl1a3NlbCIsImNvbXBhbnkiOiI2MDkxYmNkYzNlZDY4Y2JmYWQ4NzViZGIiLCJjcmVhdGVkX2F0IjoxNzQ0NzE4NDg5Ljg1NjIyNH0sIm5iZiI6MTc0NDcxODQ4OSwiZXhwIjoxNzQ3MzEwNDg5fQ.9F2guuzzYhdEpqtfYOla2UfPmQyR81UGT0G5nEwaPBE&amp;organisation_id=662bc6d80dd10297670de9f4']</value>
      <webElementGuid>62e5969c-e634-4b10-9f5f-98c75a55fd9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
