<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__leaflet-zoom-animated</name>
   <tag></tag>
   <elementGuidId>3fcbdede-5172-4bfd-9fd7-3ee5ed89ef0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.leaflet-zoom-animated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b7c61ee6-24f6-44ed-a431-cef0cba0e443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-zoom-animated</value>
      <webElementGuid>f4f56f4f-5045-4526-95ee-2547c8dc1989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>928</value>
      <webElementGuid>4c6080ea-2ac3-4177-8229-8e2df1c4aee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>283</value>
      <webElementGuid>a3d3ec9f-45ce-4998-a9d3-25d9706e9d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 928 283</value>
      <webElementGuid>3cd4ca4a-b540-4e33-9540-ea3b7ac3540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-overlay-pane&quot;]/svg[@class=&quot;leaflet-zoom-animated&quot;]</value>
      <webElementGuid>847d9a0e-a410-4fc2-a5ed-4379a927a9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Smartdeceptive/Page_/iframe_Attack Map_fullScreenAttackMap</value>
      <webElementGuid>191595b8-29ca-4a53-b4d9-6167034e3368</webElementGuid>
   </webElementProperties>
</WebElementEntity>
