<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_DDOS_lucide lucide-chevron-right h-4 w-_2b2afb</name>
   <tag></tag>
   <elementGuidId>a41baffb-90b2-4b78-bf53-fc2dc236e52e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='DDOS'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;DDOS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>642af552-7097-4ad8-8c12-b22d29441545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>aae691eb-566a-4294-9398-a6800e24d6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d9f63b2b-2eda-4963-b219-13ebdd018cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>71f33f74-f94a-4e80-964f-9a5c98291711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>257b51d6-b525-49e8-896c-09b10b134fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>3c1560e1-81a0-4a46-87ec-4f75149e76bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>fe483432-5c60-44bd-b46d-8d4a8b6bcfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e182a991-7472-4bc3-aea7-8074104e5e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>46881de8-8669-4cda-8ad8-fbfa35dc2b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>44e2fd5f-fcf1-43ee-ae9f-cf76e7efd327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-chevron-right h-4 w-4 transition-transform</value>
      <webElementGuid>60b36a57-8ec1-4230-880a-bf3ced8caa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/aside[@class=&quot;relative mr-4 hidden w-60 min-w-60 lg:block 2xl:w-80 2xl:min-w-80&quot;]/div[@class=&quot;sticky left-0 top-[89px] z-0&quot;]/div[@class=&quot;flex flex-col gap-1 rounded-md bg-card p-3 text-sm&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/button[@class=&quot;relative flex w-full items-center gap-2 rounded-md p-2 hover:bg-background-item hover:text-primary&quot;]/div[@class=&quot;flex flex-1 items-center justify-between&quot;]/svg[@class=&quot;lucide lucide-chevron-right h-4 w-4 transition-transform&quot;]</value>
      <webElementGuid>a2674cb9-d0ec-4ffe-8002-a3d8083d26d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDOS'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>048152e4-4043-4686-b784-2c91bb85d8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform IOC Discoveries'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>1cf88131-114d-4b37-ba7f-b020dd60cf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shares'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>02ad5596-3b32-44ee-abfc-9b7ba1953080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coin Search Engine'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>41d76080-064e-412f-95be-ff0ed46a93b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
