<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foreignobject</name>
   <tag></tag>
   <elementGuidId>09f6354c-15c8-4bc0-b7c2-8bae53235a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SvgjsSvg21432 > foreignobject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;SvgjsSvg21432&quot;)/foreignobject[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SvgjsSvg21432 foreignobject</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>foreignobject</value>
      <webElementGuid>c53fd7bc-4a58-4c92-84bc-5b8c75bbac97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25efa0f6-1a72-4b0b-a917-ada062a70629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4e2050df-ee15-4888-9e38-f0ea46b85ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>289</value>
      <webElementGuid>0ed4ad34-5577-4229-ad45-647136a87d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>de5d1f7a-0df8-466b-92dd-bd3100f7eff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SvgjsSvg21432&quot;)/foreignobject[1]</value>
      <webElementGuid>f196c5bf-82fb-4bfb-9598-b7ecdb0f52f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
