<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_113.27.28.61_1</name>
   <tag></tag>
   <elementGuidId>755e8746-c9bb-485b-b2a8-4c366e44e0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r15:']/div/div[2]/div[2]/div/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;113.27.28.61&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9a071be-91bf-48f5-9737-506d24d32d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative inline-flex text-sm leading-normal text-text-link no-underline transition items-center justify-between rounded-sm px-2 py-1 hover:text-primary</value>
      <webElementGuid>b3e99c12-6dac-4799-911a-cc3d98472faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c41080a6-9da8-45fd-9866-9ede2b37126c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/smartdeceptive/attack-flow?ip_address=113.27.28.61</value>
      <webElementGuid>c9aa3ab1-4577-4562-aeb4-19868e8ac963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>113.27.28.61</value>
      <webElementGuid>74424821-c0ce-4f2e-9455-419e44e36387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r15:&quot;)/div[@class=&quot;pb-4 pt-0&quot;]/div[@class=&quot;p-6 pt-0&quot;]/div[@class=&quot;grid grid-cols-1 gap-4 rounded-md bg-background-item p-4 md:grid-cols-1 lg:grid-cols-2&quot;]/div[1]/span[@class=&quot;whitespace-normal break-words&quot;]/a[@class=&quot;group relative inline-flex text-sm leading-normal text-text-link no-underline transition items-center justify-between rounded-sm px-2 py-1 hover:text-primary&quot;]</value>
      <webElementGuid>f9631791-2eec-40e9-b655-fb8321202c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r15:']/div/div[2]/div[2]/div/span[2]/a</value>
      <webElementGuid>3bbffb2b-76ed-4dc2-90d9-0051b2c62bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'113.27.28.61')]</value>
      <webElementGuid>91f3916a-09de-412d-b083-b0a9551d4d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicators:'])[1]/following::a[1]</value>
      <webElementGuid>d4222fea-be43-45a3-95f3-e6091abfe39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Detail'])[1]/following::a[1]</value>
      <webElementGuid>575c8df0-f428-4345-a2c0-9c159e3abe43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicator Name:'])[1]/preceding::a[1]</value>
      <webElementGuid>ddb08cc1-3b7d-400b-b875-4ab5b511f7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malicious IPv4 - 113.27.28.61'])[1]/preceding::a[1]</value>
      <webElementGuid>96801d7f-330c-4ae0-a2e5-7f00765c195d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/smartdeceptive/attack-flow?ip_address=113.27.28.61')]</value>
      <webElementGuid>4bbb9fd3-58c4-4712-b65e-6e7e8204448b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>662911a0-f1cc-49d0-93b4-e78d5bb60b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/smartdeceptive/attack-flow?ip_address=113.27.28.61' and (text() = '113.27.28.61' or . = '113.27.28.61')]</value>
      <webElementGuid>92d3e2ff-3a8c-4213-b5ef-79ef49dcda2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
