<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_113.27.28.61</name>
   <tag></tag>
   <elementGuidId>aad2f926-01fe-4fc0-b292-9475ab0c1395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/table/tbody/tr[2]/td/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;113.27.28.61&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>682fc1b6-84d8-4129-9445-4db7b37ef8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/threatway/signature-ioc-details/bundle--d8d134c3-fd3f-415a-9d7c-bd90b25d7d02</value>
      <webElementGuid>5eda7ebc-cd89-4e9d-8c93-52078efa1cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>501585b6-3ad1-4bfe-8b03-4528d25f036b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>113.27.28.61</value>
      <webElementGuid>02b5a065-7405-40e9-bcef-f7c5cf409d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;mt-2&quot;]/div[1]/div[@class=&quot;ant-table-wrapper css-m4timi&quot;]/div[@class=&quot;ant-spin-nested-loading css-m4timi&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table css-m4timi ant-table-ping-right ant-table-fixed-column ant-table-scroll-horizontal ant-table-has-fix-left ant-table-has-fix-right&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-fix-left ant-table-cell-fix-left-last ant-table-cell-ellipsis ant-table-cell-row-hover !bg-card !text-card-foreground&quot;]/span[@class=&quot;ant-table-cell-content&quot;]/a[@class=&quot;underline&quot;]</value>
      <webElementGuid>85535b84-e395-4555-9f67-52315e2d32ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/table/tbody/tr[2]/td/span/a</value>
      <webElementGuid>cda72b6c-a5e6-4a3a-b99b-2ccd0d77ccb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'113.27.28.61')]</value>
      <webElementGuid>e956e409-6739-4441-9c40-a7e19b491bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[1]</value>
      <webElementGuid>b10bf553-e08f-4522-9edd-8dbb4fbb3e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TLP'])[1]/following::a[1]</value>
      <webElementGuid>8b5097ec-cbbf-481a-bcc6-e6eadc1b4a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[4]/preceding::a[1]</value>
      <webElementGuid>61248208-96a1-46c8-81e5-f1a85496ed2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malicious'])[2]/preceding::a[1]</value>
      <webElementGuid>72fe9b6b-d020-4c02-9840-704499e3deec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='113.27.28.61']/parent::*</value>
      <webElementGuid>7c1fa342-e810-4d38-bfb1-ab1b96eac780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/threatway/signature-ioc-details/bundle--d8d134c3-fd3f-415a-9d7c-bd90b25d7d02')]</value>
      <webElementGuid>cdce496f-7792-4bac-8816-0bb9ca2eb377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>67a7f4f1-004a-4173-b138-a227e06a64b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/threatway/signature-ioc-details/bundle--d8d134c3-fd3f-415a-9d7c-bd90b25d7d02' and (text() = '113.27.28.61' or . = '113.27.28.61')]</value>
      <webElementGuid>7dfc2763-310e-46f8-9e58-2ad514d3ceb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
