<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>ff6ce4b9-e3ec-4beb-a078-b184bd74300c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-122 > g > g > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Malicious IPv4 - 113.27.28.61&quot;i] >> circle >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>19f43a9f-dee2-4fa1-a3e6-28fdc5ab554d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>106.22</value>
      <webElementGuid>1745c05f-969c-42f1-bc2c-a47c25e75084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-122&quot;)/g[1]/g[1]/circle[1]</value>
      <webElementGuid>17fbd005-903c-4bc4-a479-b85e32eea7bd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
