<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Risk Score_SvgjsCircle1049</name>
   <tag></tag>
   <elementGuidId>bb810797-1de9-4eda-8bbd-1841f86dbd78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SvgjsCircle1049</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//circle[@id = 'SvgjsCircle1049']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SvgjsCircle1049</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>f5d58ef5-9a1d-414d-8831-8a87db98a021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SvgjsCircle1049</value>
      <webElementGuid>491547f0-e0a3-41d3-83d5-6caf25d41d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>60.20585365853661</value>
      <webElementGuid>902bb665-2ee4-469a-b3d8-8cb0a1814be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>125.5</value>
      <webElementGuid>bc6fc003-219a-4848-9859-17861c3f9daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>125.5</value>
      <webElementGuid>97e41df3-fbd0-472f-97be-4b39f2d62dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-radialbar-hollow</value>
      <webElementGuid>5b6075a7-5933-4eb5-9dbc-9e715c83e2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>5519ccb6-1fee-4c7d-96da-4933bb04788d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SvgjsCircle1049&quot;)</value>
      <webElementGuid>c9a983ba-6440-44cb-89c2-c663551b63e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//circle[@id = 'SvgjsCircle1049']</value>
      <webElementGuid>d0676108-b903-40c2-b0a4-6dccee8cb712</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
