<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Risk Score_SvgjsCircle1354</name>
   <tag></tag>
   <elementGuidId>49506477-0fb7-4d15-a017-1530cc30ea47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SvgjsCircle1354</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//circle[@id = 'SvgjsCircle1354']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SvgjsCircle1354</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>1d391b40-7c0e-4b0c-8491-9647976999a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SvgjsCircle1354</value>
      <webElementGuid>8fc5e5a4-976d-4c5d-ab8f-1565454f3ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>65.20585365853661</value>
      <webElementGuid>f96b4866-352c-49b5-8bff-4ab1a003361c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>125.5</value>
      <webElementGuid>d0c7112a-f275-4911-b84c-31f48e6d594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>125.5</value>
      <webElementGuid>fa5e71a5-2fe4-44d3-9422-d0a18029188d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-radialbar-hollow</value>
      <webElementGuid>6dd263bb-eaae-436a-95cc-7aefcf3eeee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>0a237353-93c9-4214-8773-ce88264a725c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SvgjsCircle1354&quot;)</value>
      <webElementGuid>7d3bd1f2-50b9-4cf4-8d2c-742eae28d979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//circle[@id = 'SvgjsCircle1354']</value>
      <webElementGuid>9155cd92-6d0e-42da-a889-b97f86fa996a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
