<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No data</name>
   <tag></tag>
   <elementGuidId>9552a317-9fd6-4f19-9d80-cae8865e40f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-empty-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/table/tbody/tr[2]/td/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;No data&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20a7898d-1c22-4d7d-83bd-73b65e54b37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-empty-description</value>
      <webElementGuid>ba96f48b-ca05-4dcd-9aaa-306fe9f46500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No data</value>
      <webElementGuid>4ce290bc-a3b9-4170-a0a9-b149e098acef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;mt-2&quot;]/div[1]/div[@class=&quot;ant-table-wrapper css-m4timi&quot;]/div[@class=&quot;ant-spin-nested-loading css-m4timi&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-empty css-m4timi ant-table-ping-right ant-table-fixed-column ant-table-scroll-horizontal ant-table-has-fix-left ant-table-has-fix-right&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-placeholder&quot;]/td[@class=&quot;ant-table-cell !bg-card !text-card-foreground&quot;]/div[@class=&quot;ant-table-expanded-row-fixed&quot;]/div[@class=&quot;css-m4timi ant-empty&quot;]/div[@class=&quot;ant-empty-description&quot;]</value>
      <webElementGuid>42fa9fbf-4654-4679-afa3-96db5c7cb9d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/table/tbody/tr[2]/td/div/div/div[2]</value>
      <webElementGuid>444fae31-678d-45c7-9e24-f87ef27123aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::div[11]</value>
      <webElementGuid>8ed34e29-8a9b-4490-a619-37526f881b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TLP'])[1]/following::div[11]</value>
      <webElementGuid>cfc19ba5-9f79-45e3-a539-6834aab6f4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blogs'])[1]/preceding::div[2]</value>
      <webElementGuid>f0ee2182-d62e-4552-b5dc-4db3567667ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No data']/parent::*</value>
      <webElementGuid>e16d4100-0777-42b9-ab33-26e1bd0ac8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div[2]</value>
      <webElementGuid>74f5d9b3-ffdf-49f0-a16d-3cebff3e2aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No data' or . = 'No data')]</value>
      <webElementGuid>b1fa71e9-2e6e-4982-ad4c-56e6da90744a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
