<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllFavorites1984shabuseabuse-exporta_8ee627</name>
   <tag></tag>
   <elementGuidId>06e3c9e7-9ceb-4c9e-80ce-ef7348894222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.space-y-2.mx-4.mb-4.max-w-full > select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div/div/div/div/form/div[3]/div/div/div/div[3]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fef7cc97-595b-4bc0-89fb-d82f00209cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1fc12e48-82e8-4bf8-9970-a7a2130a7089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0c424de7-27ef-4117-9cd2-57b2de103e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllFavorites1984shabuseabuse-exportabuse-ipblocklistabuseipdbalienvaultalienvault-emailalienvault-FileHash-MD5atmosawesome-lists-system32awesome-lists-user-agents-listbambenekconsultingc2dnsbambenekconsultingc2ipbambenekconsultingdgabbcan177-4a8bf37c131be4803cb2bbcan177-bf29d47ea04391cb3eb0bigviktorbinarydefensebitcoinabusebitcoinnodesblocklistblocklist-de-apacheblocklist_de_bruteforceblocklist_de_ftpblocklist_de_imapblocklist_de_mailblocklist_de_sipblocklist_de_sshblocklist_de_strongips  ybotscoutbotscout-1dbotvrij-ioclist-domainbotvrij-ioclist-hostnamebotvrij-ioclist-ipbotvrij-ioclist-ip-rawbotvrij-ioclist-urlbotvrijEmailSrcbotvrijFilenamebotvrijMD5botvrijRegkeybotvrijSHA1botvrijSHA256bruteforceblockerC2-Tracker-data-allcategory-iocchinadciarmycobaltstrikecoin-blocker-listscompromisedconfickerCOVID-19-Malicious-Domainscryptolockercybercrime-trackercybercurecybersweatdan-me-ukdarklistdarkmapdataplane-dnsdenemedeneme2denizssch-WinKeysdisconnect_basicdisposable-email-domainsdnsversion-ipsDomain-High-Confidence-Feeddomainc2sdomainc2s-30daydomainc2s-30day-filter-abuseddomainc2s-filter-abuseddomainc2swithurldomainC2swithURL30dayfilterabuseddomainc2swithurlwithipdomainc2swithurlwithip-30daydomainc2swithurlwithip-30day-filter-abuseddshielddshielddnsdshieldipellio-ioc-ipsemergingthreatsbotccemergingthreatsdnsemergingthreatssendpointCollection12Experimental-IOC-Tweetsfeodotracker-ipblocklist-aggressivefireholfirehol-dshieldgameovergithubcontentgreensnowshashblacklisthestat-minerchkhole-cert-domainshoshsadig-adblock-nocoiniban-numbersinfosec-submissioninfoseclistdomainsinfoseclistipinfoseclisturlsinquestinquestdfiinquestiocdbIP-High-Confidence-Feedipc2s-30dayipc2s-csvipverse-asn-infojoeweinkriskintelkriskintel-domainsKrustyHack-WinKeysktsaou-blocklist-ipsetsletsgoawaydev-WinKeyslinuxtracker-hancitoripslockylokimalcodeMalicious-bitcoinMaltrailmalwaredomainlistdnsmalwaredomainlistipmaxmindmirai-ip-listMiraiIpmitchellkrogza-domains-activemitchellkrogza-links-activemitchellkrogza-links-active-nowmitchellkrogza-links-active-todaymitchellkrogza-links-new-last-hourmitchellkrogza-links-new-todaymyipnecursNeo23x0newly-registered-domainsnothinkopenphishotx-domainotxapi-BitcoinAddressotxapi-FilePath  tggotxapi-IPv6otxapi-mutexotxapi-SHA1packetmail-ramnode-ipsetphishing-domains-inactivephishing-domains-new-last-hourphishing-domains-new-todayphishing-ips-activephishing-ips-inactivephishing-ips-invalidphishing-links-inactivephishing-links-invalidphishstatsphishtankpihole-blacklistpolicemanpop3gropers-ipsproxylistsproxyrssproxyspypzb-user-agentransomwaretrackerurlRed-flag-domainsrescure-me-domain-blacklistrescure-me-malware-hashesrescureblacklistripe-asnamesripe-asnamesriproxiesrodanmaharjan-feedrstthreats-ioc-domainrstthreats-ioc-iprutgerssblam-blacklist yhsmartdeceptivesmartdeceptive-daily-mitresmartdeceptive-structuresocksproxysslipblsslproxiesstamparmstamparm-ipsumstopforumspam_toxicsuppoboxtalosintelligencetalosintelligence-iptestThe-Big-List-of-Hacked-Malware-Web-Sites-deneme_orgthreat-actor-indicatorsThreatHunting-Keywordsthreatview-MD5-HASHthreatway-sourcestofseeturristw-ip-domain-iocURL-High-Confidence-Feedurlhausurlhaus-hostfileurlvirusomviribackvirusshare-hashfiles-0virusshare-hashfiles-1virusshare-hashfiles-2virusshare-hashfiles-3evirusshare-hashfiles-4virusshare-hashfiles-5virutvoipblvxvaultwstnphxmalwareemailaddresses</value>
      <webElementGuid>391c5fa0-8be4-4e41-895e-dd1173ebaa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;flex w-full justify-between&quot;]/div[@class=&quot;flex flex-1 flex-col gap-2 lg:flex-row&quot;]/div[1]/div[@class=&quot;fixed top-[89px] z-[9] flex h-[calc(100%-89px)] w-60 flex-col bg-background transition-all duration-300 lg:block 2xl:w-80 left-24&quot;]/form[@class=&quot;flex h-[calc(100%-68px)] w-full flex-col rounded-md bg-card shadow-md&quot;]/div[@class=&quot;flex-1 overflow-hidden&quot;]/div[@class=&quot;relative overflow-hidden h-full w-full&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;space-y-2 mx-4 mb-4 max-w-full&quot;]/select[1]</value>
      <webElementGuid>d9e72f96-40c7-4d31-95f4-c51909e5f905</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div/div/div/div/form/div[3]/div/div/div/div[3]/select</value>
      <webElementGuid>47b3fab5-f59a-4d05-b4e8-e0b6ba48b469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorites'])[1]/following::select[1]</value>
      <webElementGuid>7db9a8cb-cd64-4fb7-95fa-833c3709b424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection Select :'])[1]/following::select[1]</value>
      <webElementGuid>e9e9e195-4400-4a3a-b2f2-ac260b503544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Tag Types :'])[1]/preceding::select[1]</value>
      <webElementGuid>b8046988-20b9-4692-99e2-e3f4f7267efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[4]/preceding::select[1]</value>
      <webElementGuid>fa678bf6-cf80-4ffe-8308-cc43759c9926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>6569e3a8-6102-4d72-8546-30c3fb696665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'AllFavorites1984shabuseabuse-exportabuse-ipblocklistabuseipdbalienvaultalienvault-emailalienvault-FileHash-MD5atmosawesome-lists-system32awesome-lists-user-agents-listbambenekconsultingc2dnsbambenekconsultingc2ipbambenekconsultingdgabbcan177-4a8bf37c131be4803cb2bbcan177-bf29d47ea04391cb3eb0bigviktorbinarydefensebitcoinabusebitcoinnodesblocklistblocklist-de-apacheblocklist_de_bruteforceblocklist_de_ftpblocklist_de_imapblocklist_de_mailblocklist_de_sipblocklist_de_sshblocklist_de_strongips  ybotscoutbotscout-1dbotvrij-ioclist-domainbotvrij-ioclist-hostnamebotvrij-ioclist-ipbotvrij-ioclist-ip-rawbotvrij-ioclist-urlbotvrijEmailSrcbotvrijFilenamebotvrijMD5botvrijRegkeybotvrijSHA1botvrijSHA256bruteforceblockerC2-Tracker-data-allcategory-iocchinadciarmycobaltstrikecoin-blocker-listscompromisedconfickerCOVID-19-Malicious-Domainscryptolockercybercrime-trackercybercurecybersweatdan-me-ukdarklistdarkmapdataplane-dnsdenemedeneme2denizssch-WinKeysdisconnect_basicdisposable-email-domainsdnsversion-ipsDomain-High-Confidence-Feeddomainc2sdomainc2s-30daydomainc2s-30day-filter-abuseddomainc2s-filter-abuseddomainc2swithurldomainC2swithURL30dayfilterabuseddomainc2swithurlwithipdomainc2swithurlwithip-30daydomainc2swithurlwithip-30day-filter-abuseddshielddshielddnsdshieldipellio-ioc-ipsemergingthreatsbotccemergingthreatsdnsemergingthreatssendpointCollection12Experimental-IOC-Tweetsfeodotracker-ipblocklist-aggressivefireholfirehol-dshieldgameovergithubcontentgreensnowshashblacklisthestat-minerchkhole-cert-domainshoshsadig-adblock-nocoiniban-numbersinfosec-submissioninfoseclistdomainsinfoseclistipinfoseclisturlsinquestinquestdfiinquestiocdbIP-High-Confidence-Feedipc2s-30dayipc2s-csvipverse-asn-infojoeweinkriskintelkriskintel-domainsKrustyHack-WinKeysktsaou-blocklist-ipsetsletsgoawaydev-WinKeyslinuxtracker-hancitoripslockylokimalcodeMalicious-bitcoinMaltrailmalwaredomainlistdnsmalwaredomainlistipmaxmindmirai-ip-listMiraiIpmitchellkrogza-domains-activemitchellkrogza-links-activemitchellkrogza-links-active-nowmitchellkrogza-links-active-todaymitchellkrogza-links-new-last-hourmitchellkrogza-links-new-todaymyipnecursNeo23x0newly-registered-domainsnothinkopenphishotx-domainotxapi-BitcoinAddressotxapi-FilePath  tggotxapi-IPv6otxapi-mutexotxapi-SHA1packetmail-ramnode-ipsetphishing-domains-inactivephishing-domains-new-last-hourphishing-domains-new-todayphishing-ips-activephishing-ips-inactivephishing-ips-invalidphishing-links-inactivephishing-links-invalidphishstatsphishtankpihole-blacklistpolicemanpop3gropers-ipsproxylistsproxyrssproxyspypzb-user-agentransomwaretrackerurlRed-flag-domainsrescure-me-domain-blacklistrescure-me-malware-hashesrescureblacklistripe-asnamesripe-asnamesriproxiesrodanmaharjan-feedrstthreats-ioc-domainrstthreats-ioc-iprutgerssblam-blacklist yhsmartdeceptivesmartdeceptive-daily-mitresmartdeceptive-structuresocksproxysslipblsslproxiesstamparmstamparm-ipsumstopforumspam_toxicsuppoboxtalosintelligencetalosintelligence-iptestThe-Big-List-of-Hacked-Malware-Web-Sites-deneme_orgthreat-actor-indicatorsThreatHunting-Keywordsthreatview-MD5-HASHthreatway-sourcestofseeturristw-ip-domain-iocURL-High-Confidence-Feedurlhausurlhaus-hostfileurlvirusomviribackvirusshare-hashfiles-0virusshare-hashfiles-1virusshare-hashfiles-2virusshare-hashfiles-3evirusshare-hashfiles-4virusshare-hashfiles-5virutvoipblvxvaultwstnphxmalwareemailaddresses' or . = 'AllFavorites1984shabuseabuse-exportabuse-ipblocklistabuseipdbalienvaultalienvault-emailalienvault-FileHash-MD5atmosawesome-lists-system32awesome-lists-user-agents-listbambenekconsultingc2dnsbambenekconsultingc2ipbambenekconsultingdgabbcan177-4a8bf37c131be4803cb2bbcan177-bf29d47ea04391cb3eb0bigviktorbinarydefensebitcoinabusebitcoinnodesblocklistblocklist-de-apacheblocklist_de_bruteforceblocklist_de_ftpblocklist_de_imapblocklist_de_mailblocklist_de_sipblocklist_de_sshblocklist_de_strongips  ybotscoutbotscout-1dbotvrij-ioclist-domainbotvrij-ioclist-hostnamebotvrij-ioclist-ipbotvrij-ioclist-ip-rawbotvrij-ioclist-urlbotvrijEmailSrcbotvrijFilenamebotvrijMD5botvrijRegkeybotvrijSHA1botvrijSHA256bruteforceblockerC2-Tracker-data-allcategory-iocchinadciarmycobaltstrikecoin-blocker-listscompromisedconfickerCOVID-19-Malicious-Domainscryptolockercybercrime-trackercybercurecybersweatdan-me-ukdarklistdarkmapdataplane-dnsdenemedeneme2denizssch-WinKeysdisconnect_basicdisposable-email-domainsdnsversion-ipsDomain-High-Confidence-Feeddomainc2sdomainc2s-30daydomainc2s-30day-filter-abuseddomainc2s-filter-abuseddomainc2swithurldomainC2swithURL30dayfilterabuseddomainc2swithurlwithipdomainc2swithurlwithip-30daydomainc2swithurlwithip-30day-filter-abuseddshielddshielddnsdshieldipellio-ioc-ipsemergingthreatsbotccemergingthreatsdnsemergingthreatssendpointCollection12Experimental-IOC-Tweetsfeodotracker-ipblocklist-aggressivefireholfirehol-dshieldgameovergithubcontentgreensnowshashblacklisthestat-minerchkhole-cert-domainshoshsadig-adblock-nocoiniban-numbersinfosec-submissioninfoseclistdomainsinfoseclistipinfoseclisturlsinquestinquestdfiinquestiocdbIP-High-Confidence-Feedipc2s-30dayipc2s-csvipverse-asn-infojoeweinkriskintelkriskintel-domainsKrustyHack-WinKeysktsaou-blocklist-ipsetsletsgoawaydev-WinKeyslinuxtracker-hancitoripslockylokimalcodeMalicious-bitcoinMaltrailmalwaredomainlistdnsmalwaredomainlistipmaxmindmirai-ip-listMiraiIpmitchellkrogza-domains-activemitchellkrogza-links-activemitchellkrogza-links-active-nowmitchellkrogza-links-active-todaymitchellkrogza-links-new-last-hourmitchellkrogza-links-new-todaymyipnecursNeo23x0newly-registered-domainsnothinkopenphishotx-domainotxapi-BitcoinAddressotxapi-FilePath  tggotxapi-IPv6otxapi-mutexotxapi-SHA1packetmail-ramnode-ipsetphishing-domains-inactivephishing-domains-new-last-hourphishing-domains-new-todayphishing-ips-activephishing-ips-inactivephishing-ips-invalidphishing-links-inactivephishing-links-invalidphishstatsphishtankpihole-blacklistpolicemanpop3gropers-ipsproxylistsproxyrssproxyspypzb-user-agentransomwaretrackerurlRed-flag-domainsrescure-me-domain-blacklistrescure-me-malware-hashesrescureblacklistripe-asnamesripe-asnamesriproxiesrodanmaharjan-feedrstthreats-ioc-domainrstthreats-ioc-iprutgerssblam-blacklist yhsmartdeceptivesmartdeceptive-daily-mitresmartdeceptive-structuresocksproxysslipblsslproxiesstamparmstamparm-ipsumstopforumspam_toxicsuppoboxtalosintelligencetalosintelligence-iptestThe-Big-List-of-Hacked-Malware-Web-Sites-deneme_orgthreat-actor-indicatorsThreatHunting-Keywordsthreatview-MD5-HASHthreatway-sourcestofseeturristw-ip-domain-iocURL-High-Confidence-Feedurlhausurlhaus-hostfileurlvirusomviribackvirusshare-hashfiles-0virusshare-hashfiles-1virusshare-hashfiles-2virusshare-hashfiles-3evirusshare-hashfiles-4virusshare-hashfiles-5virutvoipblvxvaultwstnphxmalwareemailaddresses')]</value>
      <webElementGuid>c9793100-4e93-4550-b653-bd93e9572054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
