<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bad Reputation</name>
   <tag></tag>
   <elementGuidId>1e6a9bba-c43f-4f69-bd4e-dc3715a54d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class, 'grid') and contains(@class, 'hover:bg-background-item')]//div[contains(@class, 'col-span-9')]//a)[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;35.226.120.32&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>009c858d-1234-4b98-9228-d7d6e0cf52e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative inline-flex items-center justify-center text-sm leading-normal text-text-link no-underline transition hover:text-text-link-hover</value>
      <webElementGuid>0a815c7e-e414-4fa1-ae6a-69241a8937ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da</value>
      <webElementGuid>823ccda2-666b-45ac-97e7-425296f100a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35.226.120.32</value>
      <webElementGuid>636d990f-c24d-4b57-af25-e59e5f8f464c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[@class=&quot;grid grid-cols-1 gap-4 max-lg:grid-cols-2 xl:grid-cols-4&quot;]/div[@class=&quot;rounded-md bg-card text-card-foreground flex h-full flex-col&quot;]/div[@class=&quot;p-6 pt-0 flex-grow&quot;]/div[@class=&quot;grid grid-cols-12 content-center items-center gap-2 border-b px-2 py-2 text-sm hover:bg-background-item&quot;]/div[@class=&quot;col-span-9 truncate xl:col-span-7&quot;]/a[@class=&quot;group relative inline-flex items-center justify-center text-sm leading-normal text-text-link no-underline transition hover:text-text-link-hover&quot;]</value>
      <webElementGuid>23a871dc-9bdf-4afa-b2dc-f1613ac67a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[4]/div[3]/div[5]/div/a</value>
      <webElementGuid>6b6ad02e-03f4-40c6-b641-c423e7dfbb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'35.226.120.32')]</value>
      <webElementGuid>82c5912a-57f2-4196-b341-4d156a319763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage'])[4]/following::a[1]</value>
      <webElementGuid>2786b20e-4d8a-4f80-b77f-630595a5ee1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captured Signatures'])[4]/following::a[1]</value>
      <webElementGuid>3f34c4c2-2c19-4571-a76d-c634b24d6a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[18]/preceding::a[1]</value>
      <webElementGuid>9587e845-5c91-4a37-8ec8-6f8c14812295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[19]/preceding::a[2]</value>
      <webElementGuid>c857e03e-2b2b-4902-8fec-ca827d92233b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35.226.120.32']/parent::*</value>
      <webElementGuid>6ffb2873-49ee-4a11-bc1b-7a125855585d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da')]</value>
      <webElementGuid>0c1555f5-2d80-4e49-9054-7566162e41ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[5]/div/a</value>
      <webElementGuid>bab645e2-e6cc-45f7-bbb5-f6c40d519945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da' and (text() = '35.226.120.32' or . = '35.226.120.32')]</value>
      <webElementGuid>87b5fd24-1db0-4042-9863-46c75cea991f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
