<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Phishing</name>
   <tag></tag>
   <elementGuidId>f0306c2c-ccdf-446f-b79b-ac02f2bce049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Phishing&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7e10184-aa83-498b-80dc-6c4c77d2ce42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold leading-none tracking-tight text-muted-foreground</value>
      <webElementGuid>26ac13f0-34b6-4e6d-a93d-3434b9e94360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phishing</value>
      <webElementGuid>7764a967-1211-4a2a-8841-eb6b42a03341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[@class=&quot;grid grid-cols-1 gap-4 max-lg:grid-cols-2 xl:grid-cols-4&quot;]/div[@class=&quot;rounded-md bg-card text-card-foreground flex h-full flex-col&quot;]/div[@class=&quot;flex flex-col space-y-1.5 p-6&quot;]/div[@class=&quot;font-semibold leading-none tracking-tight text-muted-foreground&quot;]</value>
      <webElementGuid>9882f48e-7278-473b-a588-e5a5754be8f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[3]/div/div</value>
      <webElementGuid>28a9cf87-4aba-4ab7-a23b-90150fcb9ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[17]/following::div[4]</value>
      <webElementGuid>2a60c636-4cc7-4bb8-9034-40693a2ab784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captured Signatures'])[3]/preceding::div[2]</value>
      <webElementGuid>339f5f48-911a-4d04-a852-3fd3895e7b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage'])[3]/preceding::div[5]</value>
      <webElementGuid>57080e03-4483-4577-a407-99bcb03b43c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Phishing']/parent::*</value>
      <webElementGuid>52c4d460-0acb-4f62-b3c6-723d9a7b68cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div</value>
      <webElementGuid>5252e4d3-db42-4669-bba2-9d524c2866b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Phishing' or . = 'Phishing')]</value>
      <webElementGuid>aaaf49fa-ad74-4f72-bfcd-1b312b0c0be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
