<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboard</name>
   <tag></tag>
   <elementGuidId>ac014ce9-030c-4cc0-b09a-d59fa10ae91f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'col-span-9')]//a)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39b351cb-fca6-4a74-b9ae-48002eda9ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-start</value>
      <webElementGuid>97867a0f-b3f7-492d-9116-cb58ddc20f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>72d39938-9ee6-4ab4-b0b9-f718980dad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/aside[@class=&quot;relative mr-4 hidden w-60 min-w-60 lg:block 2xl:w-80 2xl:min-w-80&quot;]/div[@class=&quot;sticky left-0 top-[89px] z-0&quot;]/div[@class=&quot;flex flex-col gap-1 rounded-md bg-card p-3 text-sm&quot;]/a[@class=&quot;relative flex w-full gap-2 rounded-md p-2 hover:bg-background-item hover:text-primary&quot;]/div[@class=&quot;flex items-center justify-start&quot;]</value>
      <webElementGuid>082a737b-efdc-4538-b6cb-5885fe81fb29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/aside/div/div/a/div[2]</value>
      <webElementGuid>883c7767-ace5-425e-b0f0-d50417004083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::div[22]</value>
      <webElementGuid>d0b45d19-056c-42d5-a990-a9dafebb4ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⌘'])[2]/following::div[22]</value>
      <webElementGuid>ead454aa-ae3e-46d7-b497-9c411cd779b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Management'])[1]/preceding::div[2]</value>
      <webElementGuid>795cf894-be02-4172-b6dc-cce48fa1d4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[1]/preceding::div[4]</value>
      <webElementGuid>8399ecdb-3677-443a-86ef-ad03c64a9dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>6ffc33be-cefb-4250-95a2-a3f793623140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>f6428508-a6e9-40b8-a5ee-c1bfce0d9cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>05f18de5-916c-423b-84dd-723ae344d574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
