<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP Digit_vi_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>b0e68bdb-c06b-4dd1-a9e5-5d76f5086948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='15517']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.vi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;verification input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1102dd62-bac1-4780-9cd0-bd293bf09961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>verification input</value>
      <webElementGuid>2e66c38a-f48a-4983-a93c-f169020ca300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c41fc1f4-d285-4937-a1dc-2e3fdfd9322d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>5258c048-57f4-4d30-9ad0-7219b61bf7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15517</value>
      <webElementGuid>1ab5dbf6-1eac-409e-9a38-84a2c65f632a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;relative h-full w-full bg-background text-sm text-foreground&quot;]/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;container relative h-full flex-col items-center justify-center md:grid lg:max-w-none lg:grid-cols-2 lg:px-0&quot;]/div[@class=&quot;flex h-full items-center lg:p-8&quot;]/div[@class=&quot;mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]&quot;]/form[@class=&quot;flex flex-col space-y-3&quot;]/div[@class=&quot;space-y-2 w-full&quot;]/div[@class=&quot;m-auto flex justify-center&quot;]/div[@class=&quot;vi__wrapper&quot;]/input[@class=&quot;vi&quot;]</value>
      <webElementGuid>af4b8b8b-f7e2-4ab7-9192-faf11bc355f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='15517']</value>
      <webElementGuid>291d8f33-a5c6-4a7d-a20f-7f968727a022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>932a4ebb-643e-40b3-ae3a-b561aad32a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
