<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Malicious</name>
   <tag></tag>
   <elementGuidId>cdd53342-a7da-43dd-b38b-3a56875f9d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class, 'grid') and contains(@class, 'hover:bg-background-item')]//div[contains(@class, 'col-span-9')]//a)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;35.226.120.32&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebb5e0a7-b503-4423-a79b-56506b4589c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative inline-flex items-center justify-center text-sm leading-normal text-text-link no-underline transition hover:text-text-link-hover</value>
      <webElementGuid>5f0c7854-c3e3-457a-8c00-2c803b5e13d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da</value>
      <webElementGuid>7a1f2dff-a59b-4abf-8bce-f02692ec6210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35.226.120.32</value>
      <webElementGuid>16e7e717-1193-4419-b9a4-fbb1486bd997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[@class=&quot;grid grid-cols-1 gap-4 max-lg:grid-cols-2 xl:grid-cols-4&quot;]/div[@class=&quot;rounded-md bg-card text-card-foreground flex h-full flex-col&quot;]/div[@class=&quot;p-6 pt-0 flex-grow&quot;]/div[@class=&quot;grid grid-cols-12 content-center items-center gap-2 border-b px-2 py-2 text-sm hover:bg-background-item&quot;]/div[@class=&quot;col-span-9 truncate xl:col-span-7&quot;]/a[@class=&quot;group relative inline-flex items-center justify-center text-sm leading-normal text-text-link no-underline transition hover:text-text-link-hover&quot;]</value>
      <webElementGuid>989cc4f3-4fee-4cf8-9151-cbfbbd84d09a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[4]/div[3]/div[5]/div/a</value>
      <webElementGuid>4b32792c-fa3a-463f-92fc-d85618f9ce80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'35.226.120.32')]</value>
      <webElementGuid>94004028-a509-4b59-ba0b-69b04d307d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage'])[4]/following::a[1]</value>
      <webElementGuid>f52aa859-9c31-4f09-87b2-33b2a9eb33cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captured Signatures'])[4]/following::a[1]</value>
      <webElementGuid>9abea906-bf78-4607-8db6-5f32997e903d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[18]/preceding::a[1]</value>
      <webElementGuid>91a3a3b8-677a-4de5-b122-6b63c90a1064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[19]/preceding::a[2]</value>
      <webElementGuid>b7675a53-9ede-4505-9731-6e334114dff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35.226.120.32']/parent::*</value>
      <webElementGuid>97d2eff6-c0f1-4b5c-9363-ff3de69e2942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da')]</value>
      <webElementGuid>e37a0325-f83b-4fd4-983e-6374d10b9e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[5]/div/a</value>
      <webElementGuid>f8324309-69e7-4c73-b143-da975e7cc775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da' and (text() = '35.226.120.32' or . = '35.226.120.32')]</value>
      <webElementGuid>bfa82e4c-defe-4bec-8036-07fdf7be91e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
