<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phishing-İp</name>
   <tag></tag>
   <elementGuidId>69107b07-43c3-421b-9934-b272a245ea02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class, 'grid') and contains(@class, 'hover:bg-background-item')]//div[contains(@class, 'col-span-9')]//a)[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;35.226.120.32&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5608b3f1-ed45-42b7-b3f0-0e261b75cfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative inline-flex items-center justify-center text-sm leading-normal text-text-link no-underline transition hover:text-text-link-hover</value>
      <webElementGuid>2c55965b-bf50-49bc-b29c-40f192410451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da</value>
      <webElementGuid>2339ba76-63d8-4f67-917d-1e96fba09c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35.226.120.32</value>
      <webElementGuid>3e98f350-953f-423e-a1ef-cdc6be2da215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[1]/div[@class=&quot;grid grid-cols-1 gap-4 max-lg:grid-cols-2 xl:grid-cols-4&quot;]/div[@class=&quot;rounded-md bg-card text-card-foreground flex h-full flex-col&quot;]/div[@class=&quot;p-6 pt-0 flex-grow&quot;]/div[@class=&quot;grid grid-cols-12 content-center items-center gap-2 border-b px-2 py-2 text-sm hover:bg-background-item&quot;]/div[@class=&quot;col-span-9 truncate xl:col-span-7&quot;]/a[@class=&quot;group relative inline-flex items-center justify-center text-sm leading-normal text-text-link no-underline transition hover:text-text-link-hover&quot;]</value>
      <webElementGuid>def46506-bc4d-4883-a297-32847df824d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div[2]/div[4]/div[3]/div[5]/div/a</value>
      <webElementGuid>4d8e84d1-aba5-41d2-80a8-4605a3880b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'35.226.120.32')]</value>
      <webElementGuid>5736b3bb-a277-417a-916e-24fe331cb22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage'])[4]/following::a[1]</value>
      <webElementGuid>cf0c485d-5824-4217-90eb-4420e5bc7543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captured Signatures'])[4]/following::a[1]</value>
      <webElementGuid>849ee918-8411-4226-ac7c-5a91d0552522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[18]/preceding::a[1]</value>
      <webElementGuid>cc70b18a-33e2-4ecc-bc48-a0628449a9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPv4'])[19]/preceding::a[2]</value>
      <webElementGuid>869284ea-07d9-47c0-81cf-586123a3a8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35.226.120.32']/parent::*</value>
      <webElementGuid>6754ac4a-bd91-4f87-9860-a3d80da242d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da')]</value>
      <webElementGuid>1d2f5fe6-3646-45ed-aa7c-e4ea8df60117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[5]/div/a</value>
      <webElementGuid>7fae7022-19dd-44db-b8df-49cac4857267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/threatway/signature-ioc-details/bundle--e9cfcd88-c29f-41ca-9295-0874a48e33da' and (text() = '35.226.120.32' or . = '35.226.120.32')]</value>
      <webElementGuid>86b49994-1b78-4633-9b04-5f9c236770d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
