<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_G_lucide lucide-webhook h-6 w-6</name>
   <tag></tag>
   <elementGuidId>fc4a9699-5a6d-42a9-a0b7-c44e0d81fe5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.lucide.lucide-webhook.h-6.w-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::*[name()='svg'][8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.h-full > div > div:nth-child(2) > button > .relative</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>3b21b2ca-303b-4c1c-8876-4e3eb551c40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>597f01bb-ec2a-4cc4-b0e4-556c60add503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>1ce3ecd7-eb36-490e-a2c6-87e1791731a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>c509f119-1abc-42cb-95aa-4c973067f844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>f153b1d9-b758-44df-8e4f-edf130481062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>105dab10-3dbb-4ccd-bb53-8be0d8240282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>ae6c9b28-5c3b-4240-92e5-b269a0aed44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7beb0fac-0581-4710-baf9-1e3c01502e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>54046934-27e8-4c6f-9697-1320dd5cdee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>8d5351a9-be44-4938-86ee-fb4c67302259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-webhook h-6 w-6</value>
      <webElementGuid>1beef939-21e8-4582-b3fc-950b5d908a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/aside[@class=&quot;fixed left-0 z-40 h-full&quot;]/nav[@class=&quot;flex h-full w-[72px] flex-col items-start justify-center border-background bg-primary bg-gradient-to-bl from-sidebar-from to-sidebar-to&quot;]/div[@class=&quot;relative overflow-hidden z-10 w-full flex-1 overflow-y-auto&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;flex items-center justify-center&quot;]/button[1]/a[@class=&quot;relative flex h-[62px] w-[72px] flex-col items-center justify-center text-primary-foreground hover:bg-primary-dark hover:text-primary-hover&quot;]/svg[@class=&quot;lucide lucide-webhook h-6 w-6&quot;]</value>
      <webElementGuid>b724f523-8358-4445-8655-106e2c6d279a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>26de15c6-3ff9-4f76-85e5-e82ef3d23ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⌘'])[2]/following::*[name()='svg'][4]</value>
      <webElementGuid>f2f76124-fb6b-48db-920b-56655f2f0dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ThreatWay'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>20b3c9a9-3e05-4008-9158-6db3c9caaba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
