<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddos_source</name>
   <tag></tag>
   <elementGuidId>62d222a9-d9fa-438e-aa52-517c9d588009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;attack-tracking&quot;]/tr[1]/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#live-attacks-table > thead > tr > th:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Source Countries&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b2ac2a1d-a4bb-4748-9581-a4fd72d98e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Source Countries</value>
      <webElementGuid>baa3d946-b941-4c30-ba61-fe1f0d76ce6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live-attacks-table&quot;)/thead[1]/tr[1]/th[2]</value>
      <webElementGuid>e5e1a979-20aa-47bd-8635-a0da2ee0504d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='live-attacks-table']/thead/tr/th[2]</value>
      <webElementGuid>6b0192d3-addb-4953-a990-15c6fb394aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::th[1]</value>
      <webElementGuid>4b71ad54-1315-474b-84e4-938c0efd11fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hedef Ülke'])[1]/following::th[2]</value>
      <webElementGuid>ff59ca85-3059-4691-abe2-d60a07c487e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source Ports'])[1]/preceding::th[1]</value>
      <webElementGuid>0b691a83-0fe9-43e3-9df6-88f18c7989f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination Countries'])[1]/preceding::th[2]</value>
      <webElementGuid>2d2fe9de-409c-464c-9e16-0e1ac296c19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Source Countries']/parent::*</value>
      <webElementGuid>1749e68b-1179-4f89-b221-8896f488e13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/thead/tr/th[2]</value>
      <webElementGuid>ffdeb11c-14a7-406f-88f3-6b9f56f7cabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Source Countries' or . = 'Source Countries')]</value>
      <webElementGuid>c6faa9e8-3f59-40a0-87c1-1eccf86117a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
