<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_DDOS Attack Map_fullScreenThreatwayA_fe63ad</name>
   <tag></tag>
   <elementGuidId>e2d49498-2d76-45df-8a5a-bb568b968aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fullScreenThreatwayAttackMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullScreenThreatwayAttackMap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Threatway DDOS Attack Map&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e7131a7c-8125-4848-b015-d7dfaae6ecbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullScreenThreatwayAttackMap</value>
      <webElementGuid>90f1809a-66a6-4975-8832-ba42e85de8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Threatway DDOS Attack Map</value>
      <webElementGuid>4a7570c8-137c-4baa-b22e-161731a5643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://threatway-map.catchprobe.org/static/en.html</value>
      <webElementGuid>f32dca00-c3ac-4acc-a080-e1bcac783889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullScreenThreatwayAttackMap&quot;)</value>
      <webElementGuid>6e45cec5-3d88-4139-8946-ce8d6cde26ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fullScreenThreatwayAttackMap']</value>
      <webElementGuid>5db2c32d-b578-4974-8fa5-a8cfa9dc6f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/iframe</value>
      <webElementGuid>5ab414dd-9912-4452-b6eb-77f417c0c6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>334b2e22-41bb-4bdb-bf2b-50239e79ea26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fullScreenThreatwayAttackMap' and @title = 'Threatway DDOS Attack Map' and @src = 'https://threatway-map.catchprobe.org/static/en.html']</value>
      <webElementGuid>c5a3cba9-d2a3-4305-8999-88c3a90ad267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
