<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keylogging</name>
   <tag></tag>
   <elementGuidId>fb888e12-d1dd-4816-bd2e-0c256fefc07e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1q3:']/div[2]/div/div/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Keylogging&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c2ad44e-7f11-4cd4-989e-02365ef0f338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:text-primary</value>
      <webElementGuid>344e0556-b3dc-4c7f-a421-308d02c6dc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/riskroute/mitre/T1056.001</value>
      <webElementGuid>d09960e1-4e27-455f-9c3a-80cbc742313f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keylogging</value>
      <webElementGuid>2ebb827e-8d33-4987-a140-c5ce22cda292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1q3:&quot;)/div[@class=&quot;h-full&quot;]/div[@class=&quot;overflow-hidden relative h-full&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;relative w-full&quot;]/div[@class=&quot;relative flex h-full flex-col pb-0&quot;]/div[@class=&quot;w-full  p-4&quot;]/div[@class=&quot;mt-4 w-[1300px]  overflow-x-auto&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative overflow-hidden&quot;]/div[@class=&quot;relative mx-auto w-full pt-10&quot;]/div[@class=&quot;flex space-x-2 overflow-hidden scroll-smooth&quot;]/div[@class=&quot;relative h-full min-w-[200px]&quot;]/div[@class=&quot;mitre-teqs grid grid-cols-1 gap-2&quot;]/div[@class=&quot;relative w-full rounded-sm bg-card p-2&quot;]/div[@class=&quot;ml-2 grid grid-cols-1 gap-2 mt-2&quot;]/div[@class=&quot;relative w-full rounded-sm border-input bg-background-item p-2 text-text-title hover:cursor-pointer hover:bg-accent hover:text-primary&quot;]/div[@class=&quot;rounded-sm px-1.5 text-xs font-semibold&quot;]/a[@class=&quot;hover:text-primary&quot;]</value>
      <webElementGuid>92d9c5ec-a902-413e-92a4-18c99babf372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1q3:']/div[2]/div/div/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div[3]/a</value>
      <webElementGuid>19d4ae54-4c59-4ad1-bef9-822816c666c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keylogging')]</value>
      <webElementGuid>ac4630ea-eae0-4eeb-bdcc-5dc07b778ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Forwarding Rule'])[1]/preceding::a[2]</value>
      <webElementGuid>c44abcd5-f7c4-414c-ba17-134e3dfca1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keylogging']/parent::*</value>
      <webElementGuid>19fc750e-4b21-4f46-b825-1768fd4dd21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/riskroute/mitre/T1056.001')]</value>
      <webElementGuid>f0c40ad7-03ef-4630-a9d4-29bf44144bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div[3]/a</value>
      <webElementGuid>789dd1b9-fb00-4650-b4a7-01bd4361035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/riskroute/mitre/T1056.001' and (text() = 'Keylogging' or . = 'Keylogging')]</value>
      <webElementGuid>b98abe6e-c35a-4afe-9203-3c9dd36de3ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
