<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_G_lucide lucide-dna h-6 w-6</name>
   <tag></tag>
   <elementGuidId>95ae8cf4-4746-461c-90cb-7c0307793712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.lucide.lucide-dna.h-6.w-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::*[name()='svg'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.h-full > div > div:nth-child(2) > button > .relative</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b920d121-369b-4769-b9a8-9b0daa3315d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b6d0d28d-f21e-47a5-b57a-eb70d750983e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>744b506d-145d-4f84-baf7-4d25d287939c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>e74ff2b5-95c4-4277-b2e5-e323b2d43c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>04e40004-c829-4b01-b59b-414d4a177273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6557850b-b81b-41dd-aaf5-627a67045e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>d096aef2-37f4-4e76-820e-218d33d9f232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>26e4e3d6-13ae-4ad2-846f-cc088a3f2718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>1e5e5b8e-e2d3-481d-92b6-4bcfbf23b2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>0a84a45e-fa8d-4ac7-b7f3-0c42252a4cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-dna h-6 w-6</value>
      <webElementGuid>d0a18ef3-deab-4318-a1f4-aaa5c26a5e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/aside[@class=&quot;fixed left-0 z-40 h-full&quot;]/nav[@class=&quot;flex h-full w-[72px] flex-col items-start justify-center border-background bg-primary bg-gradient-to-bl from-sidebar-from to-sidebar-to&quot;]/div[@class=&quot;relative overflow-hidden z-10 w-full flex-1 overflow-y-auto&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;flex items-center justify-center&quot;]/button[1]/a[@class=&quot;relative flex h-[62px] w-[72px] flex-col items-center justify-center text-primary-foreground hover:bg-primary-dark hover:text-primary-hover&quot;]/svg[@class=&quot;lucide lucide-dna h-6 w-6&quot;]</value>
      <webElementGuid>7b1cdb38-7efb-4c88-b10e-88d019df5315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>8a604a6f-1015-4bd6-bcf4-85a6d11b4a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⌘'])[2]/following::*[name()='svg'][4]</value>
      <webElementGuid>23d54d6e-80d4-4d9c-85f4-ac4d715e7165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SmartDeceptive'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7a143d87-ccfe-4783-986a-4e05d7d9a3f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
