<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Introduction</name>
   <tag></tag>
   <elementGuidId>074c249b-e49f-4e38-98b8-dbb11f675fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.toc-h1.toc-link.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='toc']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Introduction&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f66788ed-0086-4795-9ede-3adcdc2b7e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#introduction</value>
      <webElementGuid>6495feb7-c5c4-4502-8885-274eae978558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toc-h1 toc-link active</value>
      <webElementGuid>174df3c1-5a42-4512-82dc-f563e8a2ca6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Introduction</value>
      <webElementGuid>6397e63e-a337-4b5b-927b-e858d94870b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Introduction</value>
      <webElementGuid>5088f3bc-67ec-4198-b336-830ff45744c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toc&quot;)/li[1]/a[@class=&quot;toc-h1 toc-link active&quot;]</value>
      <webElementGuid>f02cac9e-6373-4d82-b08f-9ac13cfa0ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='toc']/li/a</value>
      <webElementGuid>96046a54-d348-487a-a891-721208d0b319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Introduction')]</value>
      <webElementGuid>6d75c9dc-0552-4d95-b814-c2cc3a3a2ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAV'])[1]/following::a[3]</value>
      <webElementGuid>47667e0a-f936-4b3e-b053-56e098f64632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH Endpoint'])[1]/preceding::a[1]</value>
      <webElementGuid>ffa242d9-2cb4-4697-97cd-fa04ad292d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Data'])[1]/preceding::a[2]</value>
      <webElementGuid>ac74bbfd-8606-45ee-8650-2ebbebd9d912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Introduction']/parent::*</value>
      <webElementGuid>4428d49c-2b1a-467d-a191-1a2e80cbc887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#introduction')]</value>
      <webElementGuid>feae4526-532f-493f-b865-5e4974bdf9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>a0762ac0-14b3-4692-bc1d-b0ea1a3a8cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#introduction' and (text() = 'Introduction' or . = 'Introduction')]</value>
      <webElementGuid>aad5ad34-06a7-4cc0-a296-d3701f6774d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
