<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP Digit_vi_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>678e7a15-33ea-4a15-8eba-0a6a87f3ba75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.vi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='474422']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;verification input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47aa951c-d1c3-4639-8730-1c9a8d1a30d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>verification input</value>
      <webElementGuid>0b6fe073-26cc-407b-b20e-b813769aacc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82338113-3a9c-4277-b436-227d25af7a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>f678162f-9fcd-4319-953d-26d9462d7852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>474422</value>
      <webElementGuid>445b0738-d5d3-4f51-b241-e62780aad902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;relative h-full w-full bg-background text-sm text-foreground&quot;]/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;container relative h-full flex-col items-center justify-center md:grid lg:max-w-none lg:grid-cols-2 lg:px-0&quot;]/div[@class=&quot;flex h-full items-center lg:p-8&quot;]/div[@class=&quot;mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]&quot;]/form[@class=&quot;flex flex-col space-y-3&quot;]/div[@class=&quot;space-y-2 w-full&quot;]/div[@class=&quot;m-auto flex justify-center&quot;]/div[@class=&quot;vi__wrapper&quot;]/input[@class=&quot;vi&quot;]</value>
      <webElementGuid>7be7ddaa-428f-4b11-8a4b-21008bcf5acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='474422']</value>
      <webElementGuid>6005c9e7-3cad-479d-8dff-cb656521d326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4e945318-f872-45e2-8798-86a141df9858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
