<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ignore Info Vulnerabilities_peer h-5_7854f5</name>
   <tag></tag>
   <elementGuidId>748baf9c-4a73-474e-9d3c-703446c26218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='on']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Most Common VulnerabilitiesIgnore Info Vulnerabilities$/ >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>790507e6-bc48-4003-880b-fdfbe8201f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30dc54d2-865c-417c-8eda-af188b6b8900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d8b1b2d6-bf04-4eef-80a2-3210a17c123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1de78429-d104-4e9b-a584-33be5b7075f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>c563c8f6-09dd-4b24-a0d4-8e15d6c611a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>29306b6c-d06e-4d84-96c3-374996f4ab63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer h-5 w-5 rounded-full border border-border bg-background text-text-link shadow ring-2 ring-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground</value>
      <webElementGuid>dc9cf446-8ce0-4008-ac12-5a465a89231f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[@class=&quot;relative w-full&quot;]/div[@class=&quot;relative pb-12 flex flex-col pt-4&quot;]/div[@class=&quot;grid w-full grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3&quot;]/div[@class=&quot;mb-2 rounded-md bg-card p-2 text-card-foreground md:mb-4 md:p-4 col-span-1 w-full&quot;]/div[@class=&quot;mb-2 pb-2 md:mb-4 md:flex md:pb-4 flex w-full items-center md:flex-1 border-border-primary border-b flex-col justify-start md:flex-row md:items-center md:justify-between&quot;]/div[@class=&quot;w-full text-center md:flex md:w-auto md:min-w-[100px] md:items-center md:justify-end&quot;]/div[@class=&quot;flex w-auto items-center justify-end gap-2&quot;]/div[@class=&quot;flex min-h-9 items-center gap-2&quot;]/button[@class=&quot;peer h-5 w-5 rounded-full border border-border bg-background text-text-link shadow ring-2 ring-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground&quot;]</value>
      <webElementGuid>0380c184-ea6e-44cc-a4ed-0d96d1a12435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='on']</value>
      <webElementGuid>f4cff62a-2443-408a-84ae-f70d3720a6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>b4b9c7eb-5802-4d67-bfcb-48c7d81bb229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/button</value>
      <webElementGuid>39151c32-f27c-4af0-9584-c5905c9137f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>751a5e8e-2eb3-419a-a40a-b1011ac16bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
