<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ignore Info Vulnerabilities_peer h-5_7854f5_1</name>
   <tag></tag>
   <elementGuidId>5ac8383d-63b0-4cd0-8b8c-d9ffd8b42333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='on'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Most Vulnerable TargetIgnore Info Vulnerabilities$/ >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8fbb622-e945-455d-ba80-81979559d7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b691198-bb2c-49d4-b464-d79c8f2d0061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9f10b3f3-e33e-43d0-9f33-c8beb1644536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d792978-3abf-4586-a91d-2a10edaad049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>03fabfad-0f17-49c7-aebc-82d69aa08611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6dbc9ccc-6b3e-4a3e-9fc9-91dbcdabdf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer h-5 w-5 rounded-full border border-border bg-background text-text-link shadow ring-2 ring-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground</value>
      <webElementGuid>e90233eb-0ccb-460b-a4c3-5b6e6be6a24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[@class=&quot;relative w-full&quot;]/div[@class=&quot;relative pb-12 flex flex-col pt-4&quot;]/div[@class=&quot;grid w-full grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3&quot;]/div[@class=&quot;mb-2 rounded-md bg-card p-2 text-card-foreground md:mb-4 md:p-4 col-span-1 w-full&quot;]/div[@class=&quot;mb-2 pb-2 md:mb-4 md:flex md:pb-4 flex w-full items-center md:flex-1 border-border-primary border-b flex-col justify-start md:flex-row md:items-center md:justify-between&quot;]/div[@class=&quot;w-full text-center md:flex md:w-auto md:min-w-[100px] md:items-center md:justify-end&quot;]/div[@class=&quot;flex w-auto items-center justify-end gap-2&quot;]/div[@class=&quot;flex h-9 items-center gap-2&quot;]/button[@class=&quot;peer h-5 w-5 rounded-full border border-border bg-background text-text-link shadow ring-2 ring-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground&quot;]</value>
      <webElementGuid>df705fed-e763-4136-8661-a09a96949485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='on'])[2]</value>
      <webElementGuid>736eaa65-4e5c-4d29-a7c0-dd4e35a0f483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>d5c00840-1697-474c-b909-a877a591abce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>3002d6fd-c39b-47c8-87a6-1d27a9e6c864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>e4bc922a-5431-4ef4-9f43-e9134ee22fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
