<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Count</name>
   <tag></tag>
   <elementGuidId>123a9160-3efd-4d39-bdc0-7c6fa1014419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-span-4.justify-end.text-right.flex.items-center.gap-2.text-sm.truncate.p-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Count&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0861044-714e-48fb-af41-1998b0ffb2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-span-4 justify-end text-right flex items-center gap-2 text-sm truncate p-2</value>
      <webElementGuid>3c3ee708-836e-4738-84df-ad953124e4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Count</value>
      <webElementGuid>b0188f39-eb4f-4598-8633-e39c38366db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpApp&quot;)/div[@class=&quot;ml-24 mr-4 h-full pt-[89px]&quot;]/main[@class=&quot;z-[1] h-full&quot;]/div[@class=&quot;flex h-full w-full justify-between&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;pb-6&quot;]/div[1]/div[@class=&quot;relative w-full&quot;]/div[@class=&quot;relative pb-12 flex flex-col pt-4&quot;]/div[@class=&quot;grid w-full grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3&quot;]/div[@class=&quot;mb-2 rounded-md bg-card p-2 text-card-foreground md:mb-4 md:p-4 col-span-1 w-full&quot;]/div[@class=&quot;space-y-2 text-xs text-card-foreground md:space-y-4 md:text-sm&quot;]/div[@class=&quot;relative overflow-hidden h-[300px]&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;w-full overflow-hidden overflow-x-auto p-0&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;group relative mb-2 grid grid-cols-12 gap-4 truncate font-semibold&quot;]/div[@class=&quot;col-span-4 justify-end text-right flex items-center gap-2 text-sm truncate p-2&quot;]</value>
      <webElementGuid>c3f30113-6fb2-425f-8d80-aea7f61faa6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpApp']/div[2]/main/div/div/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>7b2c17a2-e306-46c4-8a4e-fcf7c4bae8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vulnerability Name'])[1]/following::div[1]</value>
      <webElementGuid>21fcee9f-d157-4301-874d-6a74112fef16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ignore Info Vulnerabilities'])[1]/following::div[9]</value>
      <webElementGuid>e94dc81a-efc1-40d6-bbf7-4169a9c16628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weak Cipher Suites Detection'])[1]/preceding::div[1]</value>
      <webElementGuid>01b9bdf6-6471-4086-8e06-f68919796c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Netgear R6850 - Information Disclosure'])[1]/preceding::div[4]</value>
      <webElementGuid>34de5f76-02f1-4390-a9e2-408aca6f9749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Count']/parent::*</value>
      <webElementGuid>b1a9b769-bf14-4ce2-81fa-818290896b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>b90e0ee5-e402-42b1-ba9e-1577166a17c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Count' or . = 'Count')]</value>
      <webElementGuid>309eda4b-fbcb-4010-8bab-b66e5672865d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
