<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP Digit_vi_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>589a2cd7-460e-4703-8cdd-44230d644c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.vi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;verification input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bde4c917-ebdf-4d42-b10c-dba13724e7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>verification input</value>
      <webElementGuid>e1a09bd6-b335-4aa1-8d09-d81c57468aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2048a71b-c48c-4991-a5dd-398218cf4c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>4a58d1f6-492d-4135-b9da-c5539cbcc7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00000</value>
      <webElementGuid>e80328cc-8d34-4e41-800e-481dba710723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;relative h-full w-full bg-background text-sm text-foreground&quot;]/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;container relative h-full flex-col items-center justify-center md:grid lg:max-w-none lg:grid-cols-2 lg:px-0&quot;]/div[@class=&quot;flex h-full items-center lg:p-8&quot;]/div[@class=&quot;mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]&quot;]/form[@class=&quot;flex flex-col space-y-3&quot;]/div[@class=&quot;space-y-2 w-full&quot;]/div[@class=&quot;m-auto flex justify-center&quot;]/div[@class=&quot;vi__wrapper&quot;]/input[@class=&quot;vi&quot;]</value>
      <webElementGuid>2367fb92-d4cb-4c50-b8c4-193467b3d1f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='00000']</value>
      <webElementGuid>c341cd54-f8e4-4c03-bdba-cb08bde39ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>980d4f9a-6d85-45e4-b4a6-ba00c3fdb4e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
